# Unit tests for the integration dummy speech server.
#
# Copyright 2026 Igalia, S.L.
# Author: Joanmarie Diggs <jdiggs@igalia.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., Franklin Street, Fifth Floor,
# Boston MA  02110-1301 USA.

# pylint: disable=import-outside-toplevel
# pylint: disable=protected-access

"""Tests event delivery and cancellation in the integration speech server."""

from __future__ import annotations

import importlib.util
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from gi.repository import GLib

if TYPE_CHECKING:
    from collections.abc import Callable, Iterator

    from tests.integration_tests.harness.dummy_speech_server import SpeechServer

    from .orca_test_context import OrcaTestContext


@pytest.fixture
def server(test_context: OrcaTestContext) -> Iterator[SpeechServer]:
    """Loads the harness without importing application fixtures."""

    i18n = test_context.Mock()
    i18n._ = lambda value: value
    i18n.C_ = lambda _context, value: value
    i18n.ngettext = lambda singular, plural, count: singular if count == 1 else plural
    test_context.patch_module("orca.orca_i18n", i18n)

    path = Path(__file__).parents[1] / "integration_tests/harness/dummy_speech_server.py"
    spec = importlib.util.spec_from_file_location("dummy_speech_under_test", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    instance = module.SpeechServer("unit-test")
    yield instance
    instance.stop()


def _dispatch_until(predicate: Callable[[], bool]) -> None:
    """Dispatches the bounded number of ready sources created by these tests."""

    context = GLib.MainContext.default()
    for _ in range(20):
        if predicate():
            return
        assert context.pending(), "Speech stopped before completing the scenario"
        context.iteration(False)
    pytest.fail("Speech did not finish within the expected event turns")


def test_say_all_delivers_events_between_utterances(server: SpeechServer) -> None:
    """Browser events generated by speech run before the reading finishes."""

    observed = []

    def event(number: int) -> bool:
        observed.append(f"event {number}")
        return GLib.SOURCE_REMOVE

    def utterances() -> Iterator[tuple[None, None]]:
        for number in (1, 2):
            observed.append(f"utterance {number}")
            GLib.idle_add(event, number, priority=GLib.PRIORITY_DEFAULT)
            yield None, None
        observed.append("finished")

    server.say_all(utterances(), lambda *args: None)
    _dispatch_until(lambda: "finished" in observed)
    assert observed == ["utterance 1", "event 1", "utterance 2", "event 2", "finished"]


@pytest.mark.parametrize("method", ["stop", "shutdown"])
def test_stop_cancels_remaining_say_all(server: SpeechServer, method: str) -> None:
    """An interruption prevents the remaining utterances from being generated."""

    observed = []

    def utterances() -> Iterator[tuple[None, None]]:
        for number in (1, 2):
            observed.append(number)
            yield None, None

    server.say_all(utterances(), lambda *args: None)
    _dispatch_until(lambda: bool(observed))
    getattr(server, method)()
    GLib.idle_add(lambda: observed.append("done") or False)
    _dispatch_until(lambda: "done" in observed)
    assert observed == [1, "done"]


def test_new_say_all_replaces_pending_reading(server: SpeechServer) -> None:
    """Starting another reading cancels the old one before it produces output."""

    observed = []

    def utterances(label: str) -> Iterator[tuple[None, None]]:
        observed.append(label)
        yield None, None
        observed.append("finished")

    server.say_all(utterances("old"), lambda *args: None)
    server.say_all(utterances("new"), lambda *args: None)
    _dispatch_until(lambda: "finished" in observed)
    assert observed == ["new", "finished"]
