__all__ = ['Banshee',
           'Eclipse',
           'evince',
           'evolution',
           'gajim',
           'gcalctool',
           'gedit',
           'gnome-documents',
           'gnome-shell',
           'kwin',
           'notification-daemon',
           'notify-osd',
           'pidgin',
           'soffice',
           'SeaMonkey',
           'smuxi-frontend-gnome',
           'Thunderbird',
           'xfwm4']
