__all__ = ['evince',
           'evolution',
           'gajim',
           'gcalctool',
           'gedit',
           'gnome-shell',
           'kwin',
           'notification-daemon',
           'pidgin',
           'soffice',
           'SeaMonkey',
           'smuxi-frontend-gnome',
           'Thunderbird',
           'xfwm4']
