# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.browsewithcaret", true);
user_pref("app.update.auto", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1189712565);
user_pref("app.update.lastUpdateTime.background-update-timer", 1189712564);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1189712564);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1189712567);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1189712566);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.EULA.3.accepted", true);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days", 1);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.selfsupport.url", "");
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.warnOnQuit", false);
user_pref("dom.disable_window_status_change", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.testpilot.runStudies", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.enabled", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.promptOnSanitize", false);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("signon.rememberSignons", false);
user_pref("spellchecker.dictionary", "en-US");
user_pref("lightweightThemes.persisted.footerURL", false);
user_pref("lightweightThemes.persisted.headerURL", false);
user_pref("lightweightThemes.selectedThemeID", "firefox-devedition@mozilla.org");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("font.size.variable.x-western", 16);
user_pref("font.size.fixed.x-western", 16);
user_pref("font.name.sans-serif.x-western", "DejaVu Sans");
user_pref("font.name.serif.x-western", "DejaVu Serif");
user_pref("font.name.monospace.x-western", "DejaVu Sans Mono");
user_pref("xxx.legal.rights.seen", "0.0");
user_pref("browser.rights.3.shown", true);
user_pref("beagle.autoindex.active", false);
user_pref("beagle.first.run", false);
user_pref("intl.charset.default", "UTF-8");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("intl.charsetmenu.browser.static", "UTF-8");
user_pref("spellchecker.dictionary", "en_US");
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("toolkit.telemetry.enabled", false);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.tabs.remote.autostart.2", false);
pref("datareporting.healthreport.service.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.healthreport.service.firstRun", false);
pref("datareporting.healthreport.logging.consoleEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
pref("datareporting.policy.dataSubmissionPolicyAccepted; false);
